### PR TITLE
Fix issue with unevaluated `exercise` chunk option in learnr's knitr hooks

### LINKED ISSUE #757: exercise = T causes error; exercise = TRUE works
Hi,

I recently noticed the following bug: When I create an exercise chunk in a learnr tutorial and indicate it with `exercise = T`, the tutorial throws an error when I knit it (this used to work before). Everything works when I write `exercise = TRUE` instead.

`SessionInfo()`:
```R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Ventura 13.0.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] learnr_0.11.2

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.9        rstudioapi_0.14   knitr_1.40        magrittr_2.0.3    xtable_1.8-4      R6_2.5.1         
 [7] rlang_1.0.6       fastmap_1.1.0     tools_4.2.2       xfun_0.34         cli_3.6.0         withr_2.5.0      
[13] htmltools_0.5.4   ellipsis_0.3.2    yaml_2.3.6        digest_0.6.31     rprojroot_2.0.3   lifecycle_1.0.3  
[19] shiny_1.7.4       later_1.3.0       htmlwidgets_1.5.4 promises_1.2.0.1  curl_4.3.3        evaluate_0.19    
[25] mime_0.12         rmarkdown_2.18    compiler_4.2.2    jsonlite_1.8.4    httpuv_1.6.7
```

Thanks in any case for putting together this great package!

Best
Carlo

### PR DESCRIPTION
**Pull request by gadenbuie**
Fixes #757

If symbols – like `T` or a variable – are used in the `exercise` chunk option, this would cause an error in the checks that run to validate the exercise chunk by comparing with the source chunk because the source chunk options aren't yet evaluated.

This PR evaluates the source chunk option before comparing it with our exercise chunk.

### CODE REVIEW

File: R/knitr-hooks.R [hunk 1]
```diff
@@ -34,8 +34,13 @@ tutorial_knitr_options <- function() {
       return(TRUE)
     }
 
-    chunk_opts <- attr(get_knitr_chunk(label), "chunk_opts")
-    if (!identical(options$exercise, chunk_opts$exercise)) {
+    chunk_opt_exercise <- attr(get_knitr_chunk(label), "chunk_opts")[["exercise"]]
+    if (is.symbol(chunk_opt_exercise)) {
```
Comment (rossellhayes) [inline R/knitr-hooks.R:38]: How exactly does this work?

``` r
is.symbol(T)
#> [1] FALSE
```
Are the `chunk_opts` unevaluated in a way that makes that reprex not a fair comparison?

**Review by rossellhayes — APPROVED** [review]
This looks good to me! I have a question, but no concerns

File: R/knitr-hooks.R (hunk 1 above)
Comment (gadenbuie) [reply R/knitr-hooks.R:38]: It's more like this because knitr captures the chunk options without evaluating them (at least in the place where we're looking at this exact spot).

``` r
x <- quote(T)
is.symbol(x)
#> [1] TRUE
```

Comment (rossellhayes) [reply R/knitr-hooks.R:38]: Got it, thank you!
