### PR TITLE
Collect and report users's tutorial state for the current session in the Shiny app

### LINKED ISSUE #14: Obtaining assessment data (pass/fail/trials)
Glancing over the documentation, [the event recorders](https://rstudio.github.io/tutor/publishing.html#recording_events) only supply data presently for submission, error, or hint. Is there any way to obtain more granularity on this such that the outcome of the submission could be discriminate as being either correct or incorrect?

If so, then potentially the responses could be aggregated in a database and used to effectively assess students under a [Shiny Pro Server setup](https://rstudio.github.io/tutor/publishing.html#shiny_server) assuming login was required. In essence, this has the potential to be the nbgrader feature of the Jupyter notebooks but for _R_.

### PR DESCRIPTION
**Pull request by gadenbuie**
This PR addresses a common problem of tutorial app authors wanting to know the current state of the user's progress in the tutorial, for example to know which questions/exercises have received submissions, what answer was submitted and whether that answer was correct or incorrect.

To achieve this we now establish a reactive values list in `session$userData$tutorial_state` that is available to app authors in the shiny process. Authors can interact with this reactive list using `context = "server"` chunks but the reactive value is not accessible to submitted exercise code.

As implemented, the reactive list is a named list with names matching the question or exercise label and containing:

- `type`: one of `"question"` or `"exercise"`
- `answer`: the user's submitted answer as a character vector of possibly variable length
- `correct`: A logical `TRUE` or `FALSE` value of length 0 or 1. Logical `NA` values indicate the answer was not checked.
- `timestamp`: A character timestamp in UTC indicating when the event was recorded, e.g. `"2021-08-10 14:56:38.834 UTC"`.

The [`tutorial_user_state.Rmd` tutorial](https://github.com/gadenbuie/learnr/blob/reactive-current-state/sandbox/tutorial_user_state/tutorial_user_state.Rmd) in the sandbox demonstrates the structure and behavior of the `tutorial_state` reactive. Here's a snapshot:

```r
learnr::get_tutorial_state()
## List of 2
## $ two-plus-two:List of 3
##   ..$ type   : chr "exercise"
##   ..$ answer : chr "3 + 3\n\n"
##   ..$ correct: logi FALSE
##   ..# timestamp: chr "2021-08-10 14:56:38.834 UTC"
## $ quiz-1      :List of 3
##   ..$ type   : chr "question"
##   ..$ answer : chr "tools"
##   ..$ correct: logi FALSE
##   ..# timestamp: chr "2021-08-10 14:56:37.231 UTC"
```

The latest question submission is always reported, since landing on the correct answer is a terminal action. Exercise submissions are reported in the same way: submissions are always reported to the state reactive until the user reaches the correct answer. Thereafter, additional exercise submission events are ignored. (Technical note: if a student submits any code after the correct submission, the correct exercise submission event won't survive if the tutorial is reloaded in the browser.)

The final aspect of this PR is a minor change to scrub `correct` and `feedback` items from question and exercise submissions (respectively) for client storage only. For local storage, we keep these items. Regardless, the `tutorial_state` is reconstructed on tutorial start when restoring tutorial state from storage. This ensures that the `correct` flag in `tutorial_state` is accurate wrt. the current tutorial source in case the tutorial was updated after the users' state was stored. Note that when _client_ storage is used, under certain conditions, it is possible that an exercise may not be re-checked on startup.

cc @rundel The goal here is partly to give learnrhash and others an easy-to-access and lightweight representation of the current tutorial state. Rather than extracting submissions from the state objects in the tutorial storage, learnrhash can simply hash/encode the current users state of the tutorial.

## Related PRs and Issues

- Closes #393 by giving authors/developers a consistent place to find question/exercise state, including `correct`
- Closes #464 and #454 by providing an exported interface to tutorial state and info
- Closes #14 by providing pass/fail for current user. (#14 also request number of tries but it's unlikely we'll support that soon.)

### CODE REVIEW

**Comment by rundel** [comment]
Sounds great to me - I probably wont have a chance to play with it this week but I will take a look as soon as I can.

**Review by schloerke — APPROVED** [review]
Exciting!

Later we should talk about possibly exposing a `reactive()` value instead of a `reactiveVal()`, but the end user interface will not change.

Should we consider other information, like timestamp? Or should that be saved for the event logging.

File: R/initialize.R [hunk 1]
```diff
@@ -33,10 +33,14 @@ initialize_tutorial <- function() {
...
     )
 
-    # clear the setup chunk cache
+    # clear exercise/question and initialize user state reactive
     rmarkdown::shiny_prerendered_chunk(
       'server',
-      'learnr:::clear_tutorial_cache()',
+      paste(
+        'learnr:::clear_tutorial_cache()',
+        'tutorial_user_state <- reactiveValues()',
```
[the remark this answers is not in the document]
Comment (gadenbuie) [reply R/initialize.R]: I stuck with a `reactiveValues()`, but it's now stored at `session$userData$tutorial_state` (the `_user_` felt redundant)

File: R/storage.R [hunk 2]
```diff
@@ -498,3 +497,19 @@ no_storage <- function() {
...
+  if (identical(data$type, "question_submission")) {
+    data$data$correct <- NULL
+  }
+
+  if (identical(data$type, "exercise_submission")) {
+    data$data$feedback <- NULL
+  }
+
+  data
+}
```
[the remark this answers is not in the document]
Comment (gadenbuie) [reply R/storage.R]: Thanks! I updated the project setting too since this has always bugged me.

File: R/exercise.R [hunk 3]
```diff
@@ -80,16 +87,19 @@ setup_exercise_handler <- function(exercise_rx, session) {
...
+    # remove "should_check" item from exercise for legacy reasons, it's inferred downstream
+    exercise$should_check <- NULL
+
+    if (!isTRUE(check_was_requested)) {
       exercise$check <- NULL
       exercise$code_check <- NULL
       exercise$error_check <- NULL
+    } else {
+      # If there is no locally defined error check code, look for globally defined error check option
+      exercise$error_check <- exercise$error_check %||% exercise$options$exercise.error.check.code
```
[the remark this answers is not in the document]
Comment (gadenbuie) [reply R/exercise.R:101]: I think this is good. I might be over-optimizing. Line 89 merges the `exercise` input from the shiny app with the exercise object in the cache to get a full exercise object. And the `exercise.error.check.code` knit option can be used to fill in the code of the `error_chunk` globally. So before we were filling it in right after completing the exercise object to have a complete exercise object in those two lines.

I realized that we might, if we're not checking the code, immediately scrub that value, so I thought we might as well wait and only fill it in if we're actually supposed to run the checks.

In total, this particular change shouldn't change overall behavior in any way.

**Comment by gadenbuie** [comment]
A final question @schloerke: I refactored the tutorial state setting into fairly minimal `get_tutorial_state()` and `set_tutorial_state()` helpers. They're currently internal, but we might want to export `get_tutorial_state()`. It's not strictly necessary since we're using `session$userData` which is publicly available in the Shiny app. OTOH, by exporting the function we'd give ourselves a little room for future API changes. wdyt?

File: R/quiz.R [hunk 4]
```diff
@@ -304,7 +304,7 @@ knit_print.tutorial_question <- function(x, ...) {
   rmarkdown::shiny_prerendered_chunk(
     'server',
     sprintf(
-      'learnr:::question_prerendered_chunk(%s)',
+      'learnr:::question_prerendered_chunk(%s, session)',
```
Comment (schloerke) [inline R/quiz.R:307]: Matches the named arg after a `...`

```suggestion
      'learnr:::question_prerendered_chunk(%s, session = session)',
```

File: R/exercise-cache.R [hunk 5]
```diff
@@ -94,3 +95,65 @@ get_question_cache <- function(label = NULL){
...
+  if (is.reactive(data)) {
+    data <- data()
+  }
+
+  if (is.null(data)) {
+    session$userData$tutorial_state[[label]] <- NULL
+    return()
+  }
+
+  stopifnot(is.list(data), is.character(label))
```
Comment (schloerke) [inline R/exercise-cache.R:155]:
```suggestion
  stopifnot(is.character(label))
  if (is.reactive(data)) {
    data <- data()
  }

  if (is.null(data)) {
    session$userData$tutorial_state[[label]] <- NULL
    return()
  }

  stopifnot(is.list(data))
```

File: learnr.Rproj [hunk 6]
```diff
@@ -12,6 +12,7 @@ Encoding: UTF-8
 RnwWeave: Sweave
 LaTeX: pdfLaTeX
 
+AutoAppendNewline: Yes
```
Comment (schloerke) [inline learnr.Rproj:15]: Thank you!!

File: R/exercise-cache.R [hunk 7]
```diff
@@ -94,3 +95,65 @@ get_question_cache <- function(label = NULL){
...
+#'
+#'   - `type`: One of `"question"` or `"exercise"`.
+#'   - `answer`: A character vector containing the user's submitted answer(s).
+#'   - `correct`: A logical indicating whether the user's answer was correct,
+#'     or a logical `NA` if the submission was not checked for correctness.
+#'   - `timestamp`: The time at which the user's submission was completed, as
+#'     a character string in UTC, formatted as `"%F %H:%M:%OS3 %Z"`.
+#'
+#' @export
+get_tutorial_state <- function(label = NULL, session = getDefaultReactiveDomain()) {
```
Comment (schloerke) [inline R/exercise-cache.R:137]: Should re rename this to something more specific? 

`get_user_tutorial_state()` (my pick) or `get_session_tutorial_state()`

(Same for `set_tutorial_state()` below)

File: sandbox/tutorial_user_state/tutorial_user_state.Rmd [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+```
+
+
+## Topic 1
+
+The current state of your progress in this tutorial:
+
+```{r tutorial-user-state, echo=TRUE, context = "server"}
+output$tutorial_user_state <- renderPrint({
+  cat("session$userData$tutorial_state:\n")
```
Comment (schloerke) [inline sandbox/tutorial_user_state/tutorial_user_state.Rmd:26]:
```suggestion
  cat("learnr::get_tutorial_state():\n")
```

File: sandbox/tutorial_user_state/tutorial_user_state.Rmd [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+  str(reactiveValuesToList(learnr:::get_tutorial_state()))
```
Comment (schloerke) [inline sandbox/tutorial_user_state/tutorial_user_state.Rmd:27]:
```suggestion
  str(reactiveValuesToList(learnr::get_tutorial_state()))
```

**Comment by schloerke** [comment]
> OTOH, by exporting the function we'd give ourselves a little room for future API changes. wdyt?

Agreed. Let's export `get_tutorial_state()` and steer authors to only use `get_tutorial_state()`. (We should only use `session$userData$tutorial_state` internally)

File: R/exercise-cache.R (hunk 7 above)
Comment (schloerke) [reply R/exercise-cache.R:137]: I'm trying to deter confusion with "whole tutorial user submissions" vs "session specific user state"

File: R/quiz.R (hunk 4 above)
Comment (gadenbuie) [reply R/quiz.R:307]: Good catch, thank you!

File: R/exercise-cache.R (hunk 5 above)
Comment (gadenbuie) [reply R/exercise-cache.R:155]: Thanks!

File: R/exercise-cache.R (hunk 7 above)
Comment (schloerke) [reply R/exercise-cache.R:137]: "whole tutorial submissions": Essentially `learnr:::get_all_state_objects()`

That function name is oddly close to `learnr::get_tutorial_state()`

Comment (gadenbuie) [reply R/exercise-cache.R:137]: AFACT, `learnr:::get_all_state_objects()` doesn't actually keep _all_ submissions, just the most recent. E.g. if two submissions are sent for exercise `two-plus-two`, `get_all_state_objects()` will have one entry with `type = "exercise_submission"` and `id = "two-plus-two"`. I think this goes back to the `save_object()` pseudo-method of `tutorial_storage()` which doesn't appear to do any appending operations.

In that sense, `get_all_state_objects()` and `get_tutorial_state()` are practically the same thing, except that the latter "filters" for exercise and question submissions and has a more simple format.

Comment (schloerke) [reply R/exercise-cache.R:137]: Cool! Thank you

Exciting. I think we've covered the functional part of 2/3 functions in https://github.com/rstudio/learnr/pull/464 . Only `read_request()` remains

Comment (gadenbuie) [reply R/exercise-cache.R:137]: The primary need there appears to be to get the tutorial metadata. One option is to simply call `session$request$tutorial.tutorial_id` but that's not very satisfying.

Instead, I think we should refactor https://github.com/rstudio/learnr/blob/16b566de3d61f0e674c495e0e7c20708d0fc3fe6/R/exercise.R#L23-L29 into a similar helper function, e.g. `get_tutorial_metadata()` or `get_tutorial_info()`.

The tricky part with those lines is that `read_request()` isn't designed as a reactive value, but some of the values may update throughout the tutorial startup  lifecycle and/or during tutorial usage, but maybe we can follow the pattern we used here.

**Comment by schloerke** [comment]
@davidkane9 Would `learnr::get_tutorial_state()` (added in this PR) cover your needs from https://github.com/rstudio/learnr/pull/464 ? 

I believe the only functionality that isn't covered is `read_request()`

**Review by schloerke — APPROVED** [review]

File: R/exercise-cache.R (hunk 7 above)
Comment (gadenbuie) [reply R/exercise-cache.R]: I added `get_tutorial_info()` here since it's fairly related. In the end it's not a reactive variable but will find the current values from the Shiny `session` object as needed. If called outside of a reactive context it falls back to sensible defaults, either using `rmarkdown::metadata` (available during pre-render) or the default values learnr uses on initialization.

**Review by schloerke — APPROVED** [review]

**Comment by schloerke** [comment]
Now `get_tutorial_info()` handles the standard `read_request()` information from https://github.com/rstudio/learnr/pull/464

Should we close https://github.com/rstudio/learnr/pull/464?
