### PR TITLE
Remove exercise.error.checker in favor of exercise.error.check.code and -error-check chunks

### LINKED ISSUE #356: Enable tutorial.error.checker to provide checks on error
If a student submits code that throws an error, learnr exits the checking routine and displays the error message. This short circuit prevents the checking code from telling the student anything useful about what might have gone wrong. In short, the student is left to decipher the error message on his or her own.

This is necessary when the checking code relies on the result of the student code (if it throws an error, there is no result). But it is a missed opportunity when the checking code parses the unevaluated student code, as `gradethis::grade_code()` does. Here is an example, `grade_code()` would return `"I expected mtcars where you wrote mt"` but learnr displays the error message. (code appended at bottom)

Screen Shot 2020-04-23 at 2 58 41 PM

To fix this, I suggest that we:
1. Add a `tutorials.error.checker` option that can be set to a grading function to run in the event that the student code throws an error. This option can be set in the same manner as the `tutorials.exercise.checker` option. It should be set to a function that can grade the student code without evaluating it, similar to `gradethis::grade_code()`.
Screen Shot 2020-04-23 at 3 19 10 PM

 
2. Display the result of the error checking function beneath the error message. Here is a mock up. 
error-mockup 001

Code to recreate existing example above
****
````
---
title: "Example"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)

tutorial_options(exercise.checker = gradethis::grade_learnr)
knitr::opts_chunk$set(out.width = "100%")
```

## Welcome

### `mtcars`

To see the `mtcars` data frame, type `mtcars` in the code block below and click "Submit Answer".

```{r ex, exercise = TRUE}

```

```{r ex-solution}
mtcars
```

```{r ex-check}
grade_code("Good job!")
```
````

### LINKED ISSUE #425: exercise.error.checker should pass through error messages on Run Code
When the tutorial option `exercise.error.checker` is set, learnr returns an unintelligible error when a student runs bad code. Here is an example. This happens when the student clicks Run Code.

Screen Shot 2020-08-27 at 9 44 16 AM

When this option is removed, learnr displays the correct, intelligible error message when the student clicks Run Code. This is the error message you would get if you run this code at the command line.

Screen Shot 2020-08-27 at 9 44 38 AM

This may be a gradethis bug. It is clear that `gradethis::grade_learnr_error` is related to the behavior, but it is unclear if `gradethis::grade_learnr_error` should be invoked when the student clicks Run Code. See https://github.com/rstudio-education/gradethis/issues/140.

Demo .Rmd:

````
---
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(tidyverse)

tutorial_options(
  exercise.checker = gradethis::grade_learnr,
  exercise.error.checker = gradethis::grade_learnr_error
)
```

## Aesthetics

### 

Map the chape aesthetic to a continuous variable. What happens?

```{r cty3, exercise = TRUE, exercise.eval = FALSE}
# Map cty to shape
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point()
```

```{r cty3-solution}
# Map cty to shape
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, shape = cty)) + 
  geom_point()
```

```{r cty3-code-check}
grade_code("ggplot2 will map shapes to discrete variables, but not continuous variables; but that makes sense: shapes are discrete. Click Run Code to see the error message that you'll get when you map shapes to a continuous variable.")
```

````

### PR DESCRIPTION
**Pull request by cpsievert**
Fixes #356 
Fixes #425 
Fixes https://github.com/rstudio-education/gradethis/issues/140
Related https://github.com/rstudio-education/gradethis/pull/143

After feedback from @garrettgman, and discussion with @schloerke, it's becoming apparent the `exercise.error.checker` probably isn't the right approach to exercise (evaluation) error checking.

This PR replaces `exercise.error.checker` with a slightly different option, `exercise.error.check.code`, which defines what checking code to run when an exercise error occurs. This option, in some sense, provides a global default value, which can be overridden for a particular exercise with a `-error-check` chunk. Overall this seems like a much cleaner solution than `exercise.error.checker`  since it decouples error checking code from `-code-check` (pre-evaluation) and `-check` (post evaluation)

````
```{r setup, include=FALSE}
library(learnr)
library(gradethis)

tutorial_options(
  exercise.checker = gradethis::grade_learnr,
  exercise.error.check.code = "gradethis::grade_code()"
)
knitr::opts_chunk$set(echo = FALSE)
```

* Enter `mtcars`

```{r mtcars, exercise = TRUE}

```

```{r mtcars-solution}
mtcars
```

```{r mtcars-error-check}
grade_code(incorrect = "This code produces an error (press 'Run Code' to see it).", glue_incorrect = "{ .message } { .incorrect }")
```

```{r mtcars-check}
grade_result(
  fail_if(~identical(.result, cars), "This is the cars (not mtcars) dataset."),
  pass_if(~identical(.result, mtcars))
)
```
````

### CODE REVIEW

File: R/exercise.R [hunk 1]
```diff
@@ -61,13 +61,15 @@ setup_exercise_handler <- function(exercise_rx, session) {
     exercise$global_setup <- get_global_setup()
     # retrieve exercise cache information:
     # - chunks (setup + exercise) for the exercise to be processed in `evaluate_exercise`
-    # - checker code (check, code-check)
+    # - checker code (check, code-check, error-check)
     # - solution
     # - engine
     exercise <- append(exercise, get_exercise_cache(exercise$label))
+    exercise$error_check <- exercise$error_check %||% exercise$options$exercise.error.check.code
```
Comment (schloerke) [inline R/exercise.R:68]:
```suggestion
    # If there is no locally defined error check code, look for globally defined error check option
    exercise$error_check <- exercise$error_check %||% exercise$options$exercise.error.check.code
```
