### PR TITLE
Skip non-ASCII tests if system does not support UTF-8

### LINKED ISSUE #748: Test failure in strict Latin-1* locale
## From CRAN

> Dear maintainer,
> 
> Please see the problems shown on
> <https://cran.r-project.org/web/checks/check_results_learnr.html>.
> 
> Apparently your package fails its checks in a strict Latin-1* locale,
> e.g. under Linux using LANG=en_US.iso88591 (see the debian-clang
> results).
> 
> Please correct before 2022-11-16 to safely retain your package on CRAN.
> 
> Best,
> -k

## From CRAN checks

https://web.archive.org/web/20221102200837/https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/learnr-00check.html

```
  Running 'testthat.R' [59s/71s]
Running the tests in 'tests/testthat.R' failed.
Complete output:
  >
  > if (requireNamespace("testthat")) {
  + library(testthat)
  + library(learnr)
  +
  + test_check("learnr")
  + }
  Loading required namespace: testthat
  [ FAIL 1 | WARN 0 | SKIP 18 | PASS 812 ]
  
  == Skipped tests ===============================================================
  * On CRAN (18)
  
  == Failed tests ================================================================
  -- Failure ('test-exercise.R:1223'): evaluate_exercise() does not return a message for parsable non-ASCII code --
  result$feedback is not NULL
  
  `actual` is a list
  `expected` is NULL
  
  [ FAIL 1 | WARN 0 | SKIP 18 | PASS 812 ]
  Error: Test failures
  Execution halted
```

### PR DESCRIPTION
**Pull request by rossellhayes**
Previously, tests that involved non-ASCII text were skipped on Windows, with the assumption that all Unix builds of R support UTF-8. Tests now explicitly check if the system supports UTF-8 to avoid a CRAN failure on non-Unicode Unix builds. This fix is [confirmed working on rhub's debian-clang-devel platform](https://builder.r-hub.io/status/learnr_0.11.1.9000.tar.gz-f4ea6f3709d247649483019af2aeb8c8), which forces a Latin-1 (non-UTF-8) locale.

Closes #748.

### CODE REVIEW

File: tests/testthat/test-exercise.R [hunk 1]
```diff
@@ -1213,6 +1213,8 @@ test_that("evaluate_exercise() returns message for unparsable non-ASCII code", {
 test_that("evaluate_exercise() does not return a message for parsable non-ASCII code", {
   skip_if_not_pandoc("1.14")
   skip_on_os("windows")
+  # Skip if OS does not support UTF-8
+  skip_if(!isTRUE(l10n_info()[["UTF-8"]]))
```
Comment (gadenbuie) [inline tests/testthat/test-exercise.R:1217]: Should we maybe move (or copy) this test to `exercise_check_unparsable_unicode()`? https://github.com/rstudio/learnr/blob/fbc86175c427b2849b2ded718ffc9f3a670585ed/R/exercise.R#L988

**Comment by rossellhayes** [comment]
Okay, I've done some investigating on a non-UTF-8 Windows build, and here's what's going on:

The failing test involves the `exercise_check_unparseable_unicode()` function. That functions is called after a student's code fails to parse, and uses regex to find non-ASCII strings that may be responsible for the parse failure. I've tested it and it works correctly even on platforms that don't support Unicode, so the function doesn't require any edits.

This particular failing test occurred in a case where the code contains non-ASCII character but shouldn't return an error: it assigned a non-ASCII character vector to a non-ASCII (Greek) variable name, which is a valid operation. However, non-ASCII variable names can only be used on platforms with UTF-8 support.

To fix this, I've split the test into two tests. The non-ASCII character vector is tested on all platforms: it shouldn't produce a parse error on any system, since you can use Unicode characters in strings even on non-UTF-8 platforms. The non-ASCII variable name is now only tested on non-Windows platforms with UTF-8 support, since that will cause a parse error on non-UTF-8 systems.

I've tested this locally on Windows R 3.6.3 (no UTF-8 support) with no errors. I'm currently [building on non-UTF-8 Debian on R-hub](https://builder.r-hub.io/status/learnr_0.11.1.9000.tar.gz-993931878d9346db82596e1bd9d6281f).

**Review by gadenbuie — APPROVED** [review]
Thanks for the detailed investigation and the fix!
