### PR TITLE
Include a default English message for blank/unparsable errors `i18n_span()`

### LINKED ISSUE #584: Render English version of blank/unparsable error message and include as default inner text
learnr should duplicate the i18next translation in R and include the full message inside `i18n_span()`. When used in a learnr tutorial, the inner HTML will be replaced by the translation, but in cases where the translation fails there will still at least be a default value.

### PR DESCRIPTION
**Pull request by rossellhayes**
Modifies calls to `i18n_span()` in `evaluate_exercise()` to include default English text. This provides a fallback in cases where `i18next` fails to render text.

Closes #584.

### CODE REVIEW

File: R/exercise.R [hunk 1]
```diff
@@ -802,10 +802,28 @@ exercise_check_code_for_blanks <- function(exercise) {
...
+      gsub(
+        "{{count}}", length(blanks),
+        gsub(
+          "$t(text.blank)", ngettext(length(blanks), "blank", "blanks"),
+          i18n_translations()$en$translation$text$exercisecontainsblank,
+          fixed = TRUE
+        ),
+        i18n_translations()$en$translation$text$exercisecontainsblank,
+        fixed = TRUE
+      ),
```
Comment (gadenbuie) [inline R/exercise.R:814]: Perfect! Let's just pull `i18n_translations()$en$translation$text` once and then pick out `$exercisecontainsblank` and `$pleasereplaceblank` as needed afterwards.

**Review by gadenbuie — APPROVED** [review]
Awesome, thank you!

File: R/exercise.R (hunk 1 above)
Comment (rossellhayes) [reply R/exercise.R]: Fixed in ec08f13

File: R/exercise.R [hunk 2]
```diff
@@ -799,13 +799,33 @@ exercise_check_code_for_blanks <- function(exercise) {
     return(NULL)
   }
 
+  text <- i18n_translations()$en$translation$text
```
Comment (gadenbuie) [inline R/exercise.R:802]:
```suggestion
  # default message is stored in data-raw/i18n_translations.yml
  text <- i18n_translations()$en$translation$text
```
